name: CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  DOCTOR_API_PROJECT_NAME: './src/Hackathon.Fiap.Api.Doctors/Hackathon.Fiap.Api.Doctors.csproj'
  DOCTOR_API_PACKAGE_PATH: './doctors-api'

  PATIENT_API_PROJECT_NAME: './src/Hackathon.Fiap.Api.Patients/Hackathon.Fiap.Api.Patients.csproj'
  PATIENT_API_PACKAGE_PATH: './patient-api'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Publish Doctors
      run: dotnet publish ${{ env.DOCTOR_API_PROJECT_NAME }} -c Release --no-build -o ${{ env.DOCTOR_API_PACKAGE_PATH }}

    - name: Publish Doctors
      run: dotnet publish ${{ env.PATIENT_API_PROJECT_NAME }} -c Release --no-build -o ${{ env.PATIENT_API_PACKAGE_PATH }}

    - name: Upload Artifacts - Doctor
      run: echo "Here we would upload an artifact with the published at " ${{ env.DOCTOR_API_PACKAGE_PATH }}

    - name: Upload Artifacts - Patient
      run: echo "Here we would upload an artifact with the published at " ${{ env.PATIENT_API_PACKAGE_PATH }}

  deploy-doctor-api:
    name: Publish Doctors API
    needs: [build-test-publish]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checkout code"

      - run: echo "Login to Azure with CLI"

      - run: echo "Setup dotnet with global-json-file attribute"

      - run: echo "Build code"

      - run: echo "Deploy database via 'dotnet ef database update --no-build ...'"

      - run: echo "Download artifact from previous job (build-test-publish => Upload Artifacts - Doctor)"

      - run: echo "Deploy to App Service"

      - run: echo "Logout from Azure CLI"

  deploy-patient-api:
    name: Publish Patients API
    needs: [build-test-publish]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checkout code"

      - run: echo "Login to Azure with CLI"

      - run: echo "Setup dotnet with global-json-file attribute"

      - run: echo "Build code"

      - run: echo "Deploy database via 'dotnet ef database update --no-build ...'"

      - run: echo "Download artifact from previous job (build-test-publish => Upload Artifacts - Patient)"

      - run: echo "Deploy to App Service"

      - run: echo "Logout from Azure CLI"